### ISSUE TITLE
Line jumps not correctly skipped by the SRT parser

### ISSUE THREAD

**Issue by Unknow-404** [ToaHartor/GI-cutscenes#30]
`Subtitles name found: Cs_Inazuma_EQ4002207_ShikishogunRecalling_Boy
C:\Users\{UserName}\Downloads\GICutscenes\GenshinData\Subtitle\CHS\Cs_Inazuma_EQ4002207_ShikishogunRecalling_Boy_CHS.txt converted to ASS
C:\Users\{UserName}\Downloads\GICutscenes\GenshinData\Subtitle\CHT\Cs_Inazuma_EQ4002207_ShikishogunRecalling_Boy_CHT.txt converted to ASS
C:\Users\{UserName}\Downloads\GICutscenes\GenshinData\Subtitle\DE\Cs_Inazuma_EQ4002207_ShikishogunRecalling_Boy_DE.txt converted to ASS
C:\Users\{UserName}\Downloads\GICutscenes\GenshinData\Subtitle\EN\Cs_Inazuma_EQ4002207_ShikishogunRecalling_Boy_EN.txt converted to ASS
C:\Users\{UserName}\Downloads\GICutscenes\GenshinData\Subtitle\ES\Cs_Inazuma_EQ4002207_ShikishogunRecalling_Boy_ES.txt converted to ASS
C:\Users\{UserName}\Downloads\GICutscenes\GenshinData\Subtitle\FR\Cs_Inazuma_EQ4002207_ShikishogunRecalling_Boy_FR.txt converted to ASS
Unhandled exception: System.Exception: Dialogue block doesn't start with a number
   at GICutscenes.FileTypes.ASS.ParseSrt()
   at GICutscenes.Program.MergeFiles(String outputPath, String basename, String engine, Boolean subs)
   at GICutscenes.Program.BatchDemuxCommand(DirectoryInfo inputDir, DirectoryInfo outputDir, String engine, Boolean merge, Boolean subs, Boolean noCleanup)
   at GICutscenes.Program.<>c.<<Main>b__1_1>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext )
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass18_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass13_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass20_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__19_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__6_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass9_0.<<UseExceptionHandler>b__0>d.MoveNext()`

**Comment by Unknow-404** [comment]
What is the problem?

**Comment by ToaHartor** [comment]
Okay so this error happened on the language after FR, so ID. Pretty sure it's because the srt parser doesn't handle a specific case. You  will be able to fix it by removing the double line jumps.

Try to have this
```
7
00:00:24,150 --> 00:00:25,825
"pencapaian tertinggi" ini?

8
00:00:26,875 --> 00:00:28,200
Mengapa begitu gelisah
```
Instead of this
```
7
00:00:24,150 --> 00:00:25,825
"pencapaian tertinggi" ini?


8
00:00:26,875 --> 00:00:28,200
Mengapa begitu gelisah
```

I'll try to make a fix that might be reelased for the next version, but tbh it's mainly due to MHY not being able to make correctly formatted subtitles.

**Comment by Unknow-404** [comment]
OK, thanks!

**Comment by ToaHartor** [comment]
Should be fixed in the new version.
