### ISSUE TITLE
Unhandled exception. System.IO.InvalidDataException: Failed to load configuration from file

### ISSUE THREAD

**Issue by WuYanFall** [ToaHartor/GI-cutscenes#31]
Unhandled exception. System.IO.InvalidDataException: Failed to load configuration from file 'C:\Users\\***\Downloads\GICutscenes-0.4.0-win-x64-standalone\appsettings.json'.
 ---> System.FormatException: Could not parse the JSON file.
 ---> System.Text.Json.JsonReaderException: 'M' is an invalid escapable character within a JSON string. The string should be correctly escaped. LineNumber: 2 | BytePositionInLine: 24.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& , ExceptionResource , Byte , ReadOnlySpan`1 )
   at System.Text.Json.Utf8JsonReader.ConsumeStringAndValidate(ReadOnlySpan`1 , Int32 )
   at System.Text.Json.Utf8JsonReader.ConsumeString()
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte )
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.JsonDocument.Parse(ReadOnlySpan`1 , JsonReaderOptions , MetadataDb& , StackRowStack& )
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 , JsonReaderOptions , Byte[] , PooledByteBufferWriter )
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 , JsonDocumentOptions )
   at System.Text.Json.JsonDocument.Parse(String , JsonDocumentOptions )
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationFileParser.ParseStream(Stream )
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load(Stream )
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load(Stream )
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean )
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.HandleException(ExceptionDispatchInfo )
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean )
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 )
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at GICutscenes.Program.Main(String[] args)

**Comment by ToaHartor** [comment]
> ---> System.Text.Json.JsonReaderException: 'M' is an invalid escapable character within a JSON string. The string should be correctly escaped. LineNumber: 2 | BytePositionInLine: 24.

How does your configuration file look like ?

**Comment by WuYanFall** [comment]
![QQ截图20220808192622](https://user-images.githubusercontent.com/110774425/183407866-afa8f8c3-fc32-4c12-bbcb-1abb82998a7d.png)

**Comment by ToaHartor** [comment]
Alright, so the problem is due to the path format, putting single backslashes `\` makes the format think that you tried to escape characters.

Therefore there are two solutions to this problem, either use slashes `/` or escaped back slashes `\\` instead.

**Comment by WuYanFall** [comment]
very thanks
