### ISSUE TITLE
Unable to export cutscenes for version 3.0

### ISSUE THREAD

**Issue by AlbertWen-AW** [ToaHartor/GI-cutscenes#38]
When I select a cutscene in Genshin Impact 3.0, I get the following results, but there is no file in the Output Folder

```
Output folder : D:\1\GICutscenes_win-x64_standalone\output
Finding encryption key for Cs_Sumeru_AQ30130101_DofFG_Boy.usm...
Unhandled exception: System.Collections.Generic.KeyNotFoundException: Unable to find the second key in versions.json for Cs_Sumeru_AQ30130101_DofFG_Boy
at GICutscenes.Demuxer.EncryptionKeyInBLK(String videoFilename)
at GICutscenes.Demuxer.EncryptionKey(String videoFilename)
at GICutscenes.Demuxer.Demux(String filenameArg, Byte[] key1Arg, Byte[] key2Arg, String output)
at GICutscenes.Program.BatchDemuxCommand(DirectoryInfo inputDir, DirectoryInfo outputDir, String engine, Boolean merge, Boolean subs, Boolean noCleanup)
at GICutscenes.Program.<>c.<<Main>b__1_1>d.MoveNext()
--- End of stack trace from previous location ---
at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext )
at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass18_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass13_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass20_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__19_0>d.MoveNext()
--- End of stack trace from previous location ---
at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__6_0>d.MoveNext()
--- End of stack trace from previous location ---
at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass9_0.<<UseExceptionHandler>b__0>d.MoveNext()

Starting ffmpeg
Working ffmpeg...
D:/1/GICutscenes_win-x64_standalone/output\Cs_Sumeru_AQ30130101_DofFG_Boy.m2v: No such file or directory
Merging complete!
```
But the cutscenes I exported for version 2.7 and before were fine (After update 3.0, there are no cutscenes from version 2.8 in the directory.)

These are the only four cutscenes that can't be exported properly, Look at the time is version 3.0 update
![image](https://user-images.githubusercontent.com/106954672/188258681-18f75985-d75b-450c-bedd-0944ef77246b.png)

**Comment by AlbertWen-AW** [comment]
And these seem to be version 2.8 updates and can't be exported either
![image](https://user-images.githubusercontent.com/106954672/188259305-d6073786-b7db-419b-8c03-a3bd52cecb52.png)

**Comment by BUnipendix** [comment]
检查一下version.json文件有没有更新，错误显示是找不到密钥

**Comment by AlbertWen-AW** [comment]
> 检查一下version.json文件有没有更新，错误显示是找不到密钥
我下载的是这个文件，version.json文件也是这其中的，7月3日的文件
https://github.com/ToaHartor/GI-cutscenes/releases/download/v0.4.0/GICutscenes-0.4.0-win-x64-standalone.zip

**Comment by AlbertWen-AW** [comment]
哦，我知道了，最新的在主目录下8天前更新的那个是吧，搞定了，谢谢

**Comment by ToaHartor** [comment]
Yes, the `versions.json` shipped with the last release isn't up to date, so you have to get the `versions.json` from the repository (a direct link is available in the README iirc).
For the next release, I was thinking about integrating an updater able to download the last version available.
