### ISSUE TITLE
No ASS file could be found but two files were matched previously

### ISSUE THREAD

**Issue by southrop** [ToaHartor/GI-cutscenes#52]
I encountered an exception when re-converting some older videos. From what I can tell, an update two months ago added SRT subtitles for a lot of videos in some languages, such as [Japanese](https://github.com/Dimbreath/GenshinData/tree/master/Subtitle/JP). These videos had subtitles previously in SRT format, but the extension was TXT, so this causes this exception to trigger.

```
Subtitles name found: Ambor_Readings
Unhandled exception: System.IO.FileNotFoundException: No ASS file could be found for the subs Ambor_Readings, but two files were matched previously, please report this case.
   at GICutscenes.Program.MergeFiles(String outputPath, String basename, String engine, Boolean subs)
   at GICutscenes.Program.BatchDemuxCommand(DirectoryInfo inputDir, DirectoryInfo outputDir, String engine, Boolean merge, Boolean subs, Boolean noCleanup)
   at GICutscenes.Program.<>c.<<Main>b__1_1>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext )
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass18_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass13_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass20_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__19_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__6_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass9_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

**Comment by ToaHartor** [comment]
Should be the same issue as #39, it has been fixed on the main branch but not on the actual release.

**Comment by southrop** [comment]
Ah, so it is. Sorry for the duplicate!
