### ISSUE TITLE
System.Exception: Language code IT isn't supported...

### ISSUE THREAD

**Issue by steven52880** [ToaHartor/GI-cutscenes#76]
```
GICutscenes demuxUsm ".\input\Cs_Inazuma_EQ_4009004_DYG1.usm" --merge --output .\output -e ffmpeg --subs


Output folder : G:\Genshin\GICutscenes-0.4.0\output
Finding encryption key for Cs_Inazuma_EQ_4009004_DYG1.usm...
key1=B0E1E6F8 key2=47C61000
Demuxing Cs_Inazuma_EQ_4009004_DYG1.usm : extracting video and audio...
Converting Cs_Inazuma_EQ_4009004_DYG1_3.hca to wav...
Converting Cs_Inazuma_EQ_4009004_DYG1_1.hca to wav...
Converting Cs_Inazuma_EQ_4009004_DYG1_0.hca to wav...
Converting Cs_Inazuma_EQ_4009004_DYG1_2.hca to wav...
Extraction completed !
Merging using ffmpeg.
Subtitles name found: Cs_Inazuma_EQ_4009004_DYG1
Using subs file Cs_Inazuma_EQ_4009004_DYG1_CHS.ass
Using subs file Cs_Inazuma_EQ_4009004_DYG1_CHT.ass
Using subs file Cs_Inazuma_EQ_4009004_DYG1_DE.ass
Using subs file Cs_Inazuma_EQ_4009004_DYG1_EN.ass
Using subs file Cs_Inazuma_EQ_4009004_DYG1_ES.ass
Using subs file Cs_Inazuma_EQ_4009004_DYG1_FR.ass
Using subs file Cs_Inazuma_EQ_4009004_DYG1_ID.ass
Using subs file Cs_Inazuma_EQ_4009004_DYG1_IT.ass
Unhandled exception: System.Exception: Language code IT isn't supported...
   at GICutscenes.Mergers.FFMPEG.AddSubtitlesTrack(String subFile, String language)
   at GICutscenes.Program.MergeFiles(String outputPath, String basename, String engine, Boolean subs)
   at GICutscenes.Program.DemuxUsmCommand(FileInfo file, String key1, String key2, DirectoryInfo output, String engine, Boolean merge, Boolean subs, Boolean noCleanup)
   at GICutscenes.Program.<>c.<<Main>b__1_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext )
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass18_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass13_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass20_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__19_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__6_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass9_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

**Comment by yuboyan2007** [comment]
I found a temporary solution , you can leave only CHS and EN in the Subtitle folder . I hope it can help you .

**Comment by ToaHartor** [comment]
Added with #68, will close on the next release.
