### ISSUE TITLE
I cannot execute exe

### ISSUE THREAD

**Issue by edmxn** [ToaHartor/GI-cutscenes#81]
I've been trying to do research on my own for a long time now and it led me to this.

I have Windows 11 x64
When I double click the exe, it opens for a few seconds showing this and then closes.
![Captura de pantalla (73)](https://user-images.githubusercontent.com/101371218/213913691-d6aa0a68-20f1-47c6-9c7a-a33b067c84de.png)
Ignore the selected, as it is removed quickly, I take the capture fast

I don't know much about programming or anything like that, but I want this, so I'm trying

**Comment by Unknow-404** [comment]
It's a command line program, you should use the command instead of double click the exe.f

**Comment by edmxn** [comment]
> It's a command line program, you should use the command instead of double click the exe.

And how do I use the command? and where is that command? Thanks

**Comment by Unknow-404** [comment]
> > It's a command line program, you should use the command instead of double click the exe.
> 
> And how do I use the command? and where is that command? Thanks

Please read [README.md](https://github.com/ToaHartor/GI-cutscenes/blob/main/README.md) to learn how to use it.

**Comment by edmxn** [comment]
> > > It's a command line program, you should use the command instead of double click the exe.
> > 
> > 
> > And how do I use the command? and where is that command? Thanks
> 
> Please read [README.md](https://github.com/ToaHartor/GI-cutscenes/blob/main/README.md) to learn how to use it.

I did it, but I still don't understand... Where do I execute the commands? In GIT? There when I type a command I get nothing, or rather I get something like that command does not exist (Git Bash)

**Comment by jerichosy** [comment]
Use standalone version

**Comment by jerichosy** [comment]
> > > > It's a command line program, you should use the command instead of double click the exe.
> > > 
> > > 
> > > And how do I use the command? and where is that command? Thanks
> > 
> > 
> > Please read [README.md](https://github.com/ToaHartor/GI-cutscenes/blob/main/README.md) to learn how to use it.
> 
> I did it, but I still don't understand... Where do I execute the commands? In GIT? There when I type a command I get nothing, or rather I get something like that command does not exist (Git Bash)

Use the standalone version. Then, open cmd in the directory where `GICutscenes.exe` is located (either by typing cmd in the path bar or right-click in the folder -> "Open in Terminal". Then it's as simple as following the [README.md](https://github.com/ToaHartor/GI-cutscenes/blob/main/README.md) (look at the [examples](https://github.com/ToaHartor/GI-cutscenes#examples)). If this is too hard for you to grasp, I suggest using the [GUI version](https://github.com/SuperZombi/GICutscenesUI).

**Comment by edmxn** [comment]
> > > > > It's a command line program, you should use the command instead of double click the exe.
> > > > 
> > > > 
> > > > And how do I use the command? and where is that command? Thanks
> > > 
> > > 
> > > Please read [README.md](https://github.com/ToaHartor/GI-cutscenes/blob/main/README.md) to learn how to use it.
> > 
> > 
> > I did it, but I still don't understand... Where do I execute the commands? In GIT? There when I type a command I get nothing, or rather I get something like that command does not exist (Git Bash)
> 
> Use the standalone version. Then, open Command Prompt in the directory where `GICutscenes.exe` is located (either by typing cmd in the path bar or right-click in the folder -> "Open in Terminal". Then it's as simple as following the [README.md](https://github.com/ToaHartor/GI-cutscenes/blob/main/README.md) (look at the [examples](https://github.com/ToaHartor/GI-cutscenes#examples)). If this is too hard for you to grasp, I suggest using the [GUI version](https://github.com/SuperZombi/GICutscenesUI).

i get this on gui 

Finding encryption key for Cs_Liyue_EQ4009306_HDJ1.usm...
Unhandled exception: System.Collections.Generic.KeyNotFoundException: Unable to find the second key in versions.json for Cs_Liyue_EQ4009306_HDJ1
at GICutscenes.Demuxer.EncryptionKeyInBLK(String videoFilename) in /home/runner/work/GI-cutscenes/GI-cutscenes/src/Demuxer.cs:line 54
at GICutscenes.Demuxer.EncryptionKey(String videoFilename) in /home/runner/work/GI-cutscenes/GI-cutscenes/src/Demuxer.cs:line 66
at GICutscenes.Demuxer.Demux(String filenameArg, Byte[] key1Arg, Byte[] key2Arg, String output) in /home/runner/work/GI-cutscenes/GI-cutscenes/src/Demuxer.cs:line 91
at GICutscenes.Program.BatchDemuxCommand(DirectoryInfo inputDir, DirectoryInfo outputDir, String engine, Boolean merge, Boolean subs, Boolean noCleanup) in /home/runner/work/GI-cutscenes/GI-cutscenes/src/Program.cs:line 180
at GICutscenes.Program.<>c.<<Main>b__1_1>d.MoveNext() in /home/runner/work/GI-cutscenes/GI-cutscenes/src/Program.cs:line 135
--- End of stack trace from previous location ---
at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext )
at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---

the latter is repeated

**Comment by jerichosy** [comment]
> > > > > > It's a command line program, you should use the command instead of double click the exe.
> > > > > 
> > > > > 
> > > > > And how do I use the command? and where is that command? Thanks
> > > > 
> > > > 
> > > > Please read [README.md](https://github.com/ToaHartor/GI-cutscenes/blob/main/README.md) to learn how to use it.
> > > 
> > > 
> > > I did it, but I still don't understand... Where do I execute the commands? In GIT? There when I type a command I get nothing, or rather I get something like that command does not exist (Git Bash)
> > 
> > 
> > Use the standalone version. Then, open Command Prompt in the directory where `GICutscenes.exe` is located (either by typing cmd in the path bar or right-click in the folder -> "Open in Terminal". Then it's as simple as following the [README.md](https://github.com/ToaHartor/GI-cutscenes/blob/main/README.md) (look at the [examples](https://github.com/ToaHartor/GI-cutscenes#examples)). If this is too hard for you to grasp, I suggest using the [GUI version](https://github.com/SuperZombi/GICutscenesUI).
> 
> i get this on gui
> 
> Finding encryption key for Cs_Liyue_EQ4009306_HDJ1.usm... Unhandled exception: System.Collections.Generic.KeyNotFoundException: Unable to find the second key in versions.json for Cs_Liyue_EQ4009306_HDJ1 at GICutscenes.Demuxer.EncryptionKeyInBLK(String videoFilename) in /home/runner/work/GI-cutscenes/GI-cutscenes/src/Demuxer.cs:line 54 at GICutscenes.Demuxer.EncryptionKey(String videoFilename) in /home/runner/work/GI-cutscenes/GI-cutscenes/src/Demuxer.cs:line 66 at GICutscenes.Demuxer.Demux(String filenameArg, Byte[] key1Arg, Byte[] key2Arg, String output) in /home/runner/work/GI-cutscenes/GI-cutscenes/src/Demuxer.cs:line 91 at GICutscenes.Program.BatchDemuxCommand(DirectoryInfo inputDir, DirectoryInfo outputDir, String engine, Boolean merge, Boolean subs, Boolean noCleanup) in /home/runner/work/GI-cutscenes/GI-cutscenes/src/Program.cs:line 180 at GICutscenes.Program.<>c.<
> 
> b__1_1>d.MoveNext() in /home/runner/work/GI-cutscenes/GI-cutscenes/src/Program.cs:line 135
> --- End of stack trace from previous location ---
> at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext )
> at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<b__0>d.MoveNext()
> --- End of stack trace from previous location ---
> the latter is repeated

The `versions.json` file which contains the decryption keys has not yet been updated in this repository. Download (right-click -> Save as) this updated [`versions.json`](https://raw.githubusercontent.com/Asnxthaony/GI-cutscenes/main/versions.json) file instead from a fork.

**Comment by ToaHartor** [comment]
Thinking about this, if the behaviour of double-clicking on the exe was to open a command prompt with the help page, would it make the tool easier to use ?

**Comment by ElysiaFLOPS** [comment]
> Thinking about this, if the behaviour of double-clicking on the exe was to open a command prompt with the help page, would it make the tool easier to use ?

i think it's a good idea，It would be better if it supports multiple languages

**Comment by mchubby** [comment]
Hello,
I found a similar error message while using the non-standalone version on Windows (tested on 0.4.1 too).

Weirdly enough, when using the standalone version and not providing any parameter, the program properly displays the usage help message.
Also, the place shown by the stacktrace seems to indicates the error takes place within the System.CommandLine assembly.

Non-standalone version:
```
.\GICutscenes.exe
Required command was not provided.

Unhandled exception. System.TypeLoadException: Method 'get_Encoding' in type 'TextWriterThatWritesToStandardStreamWriter' from assembly 'System.CommandLine, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
   at System.CommandLine.IO.StandardStreamWriter.CreateTextWriter(IStandardStreamWriter )
   at System.CommandLine.Help.HelpResult.Apply(InvocationContext )
   at System.CommandLine.Invocation.ParseErrorResult.Apply(InvocationContext )
   at System.CommandLine.Invocation.InvocationPipeline.GetExitCode(InvocationContext )
   at System.CommandLine.Invocation.InvocationPipeline.Invoke(IConsole )
   at System.CommandLine.Parsing.ParserExtensions.Invoke(Parser , String[] , IConsole )
   at GICutscenes.Program.Main(String[] args) in /home/runner/work/GI-cutscenes/GI-cutscenes/src/Program.cs:line 216
```

https://github.com/ToaHartor/GI-cutscenes/blob/addc5f97cf29c1f9cbbdd33ab58e4b77528de2ec/src/Program.cs#L216-L228

Reproduced on both:
```powershell
$PSVersionTable.PSVersion | fl

Major           : 7
Minor           : 3
Patch           : 2
PreReleaseLabel :
BuildLabel      :

$PSVersionTable.PSVersion | fl

Major         : 5
Minor         : 1
Build         : 19041
Revision      : 1237
MajorRevision : 0
MinorRevision : 1237


```
(yes it's a bit old W10)
